name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: invoke build

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Deploy
        env:
          DEPLOY_REPO: https://${{ secrets.ACTIONS_GITHUB_TOKEN  }}@github.com/music-presence/live.git
        run: invoke deploy
