name: deploy

on: [push]

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/upload-artifact@v4
        with:
          path: configure

  build:
    runs-on: ubuntu-latest
    needs: configure
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: configure
      - name: Build
        run: invoke build

  deploy:
    runs-on: ubuntu-latest
    needs: configure
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: configure
      - name: Deploy
        env:
          DEPLOY_REPO: https://${{ secrets.ACTIONS_GITHUB_TOKEN  }}@github.com/music-presence/live.git
        run: invoke deploy
